// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl3TKTNP-6phYf2bHpRkwuI443lDbtE38',
    appId: '1:525960282942:web:4ae8210bd940fc9ac8226f',
    messagingSenderId: '525960282942',
    projectId: 'sih-2023-7046a',
    authDomain: 'sih-2023-7046a.firebaseapp.com',
    storageBucket: 'sih-2023-7046a.appspot.com',
    measurementId: 'G-RBHCFQBFTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPV4zrbORBjs0RzmXrEhLVORUVP8uq8dg',
    appId: '1:525960282942:android:56b7b5c30615c6c5c8226f',
    messagingSenderId: '525960282942',
    projectId: 'sih-2023-7046a',
    storageBucket: 'sih-2023-7046a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXJ1zmCWOcpd_kQwNOIozFGTSC2fM7WDw',
    appId: '1:525960282942:ios:53f1dd5fb4605cfec8226f',
    messagingSenderId: '525960282942',
    projectId: 'sih-2023-7046a',
    storageBucket: 'sih-2023-7046a.appspot.com',
    iosBundleId: 'com.example.sih2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXJ1zmCWOcpd_kQwNOIozFGTSC2fM7WDw',
    appId: '1:525960282942:ios:2dd2f0d8cb9a86cec8226f',
    messagingSenderId: '525960282942',
    projectId: 'sih-2023-7046a',
    storageBucket: 'sih-2023-7046a.appspot.com',
    iosBundleId: 'com.example.sih2023.RunnerTests',
  );
}
